topTable<-function(models,contrast)
{
out<-data.frame(
logFC=sapply(models,getContrast,L=contrast),
se=sqrt(sapply(models,varContrast,L=contrast)),
df=sapply(models,getDfPosterior)
)
out$t<-out$logFC/out$se
out$pval<-pt(-abs(out$t),out$df)*2
out$adjPval<-p.adjust(out$pval,method="fdr")
return(out)
}
